name: jsonschema_form
description: A Flutter package capable of using JSON Schema to declaratively
  build and customize Flutter forms
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ^3.27.3

dependencies:
  camera: ^0.11.0+2
  collection: ^1.18.0
  equatable: ^2.0.3
  extended_image: ^9.1.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_thumbnail_video: ^0.7.3
  html: ^0.15.5
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  mime: ^2.0.0
  omni_datetime_picker: ^2.0.5
  path: ^1.9.0
  path_provider: ^2.1.5
  phone_form_field: ^10.0.3
  video_player: ^2.9.2 # or the latest version
  video_player_web: 2.3.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
